(function(){
	var header = document.getElementById('header');
	
var str = ["				<!--头部开始-->",
"		<nav class=\"navbar navbar-fixed-top nav-bg\">",
"			<div class=\"container\">",
"				<!-- Brand and toggle get grouped for better mobile display -->",
"				<div class=\"navbar-header\">",
"					<button type=\"button\" class=\"navbar-toggle collapsed \" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\" aria-expanded=\"false\">",
"				        <span class=\"sr-only\" style=\"border: 1px silver solid;\">Toggle navigation</span>",
"				        <span class=\"icon-bar\"></span>",
"				        <span class=\"icon-bar\"></span>",
"				        <span class=\"icon-bar\"></span>",
"				     </button>",
"					<a class=\"navbar-brand\" href=\"#\">",
"						<img alt=\"Brand\" src=\"img/logo.png\">",
"					</a>",
"				</div>",
"				<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">",
"					<ul class=\"nav navbar-nav nav-center\">",
"						<li class=\"active\">",
"							<a href=\"index.html\">Top <span class=\"sr-only\">(current)</span></a>",
"						</li>",
"						<li>",
"							<a href=\"#\">About</a>",
"						</li>",
"						<li>",
"							<a href=\"#\">Products</a>",
"						</li>",
"						<li>",
"							<a href=\"projects.html\">Projects</a>",
"						</li>",
"						<li>",
"							<a href=\"#\">Clients</a>",
"						</li>",
"						<li>",
"							<a href=\"recruitment.html\">Recruitment</a>",
"						</li>",
"						<li>",
"							<a href=\"#\">Contacts</a>",
"						</li>",
"					</ul>",
"					<hr />",
"					<ul class=\"nav navbar-nav navbar-right search\">",
"						<li>",
"							<a href=\"#\">CN/EN</a>",
"						</li>",
"						<li>",
"							<a href=\"#\">SEARCH</a>",
"						</li>",
"					</ul>",
"				</div>",
"				<!-- /.navbar-collapse -->",
"			</div>",
"			<!-- /.container-fluid -->",
"		</nav>",
"		<!--头部结束-->"].join("");
		
		
		header.innerHTML = str;
})(document);
